[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "npx prisma generate --schema=apps/backend/prisma/schema.prisma"
]

[phases.build]
cmds = [
  "npm run build:prod:frontend",
  "npm run build:prod:backend"
]

[start]
cmd = "npx prisma migrate deploy --schema=apps/backend/prisma/schema.prisma && node dist/apps/backend/main.js"
